.TH "dispcalGUI-VRML-to-X3D-converter" "1" "12 Apr 2014" "" ""

.SH NAME
dispcalGUI-VRML-to-X3D-converter \- VRML to X3D converter
.SH SYNOPSIS

\fBdispcalGUI-VRML-to-X3D-converter\fR

.SH "DESCRIPTION"
.PP
Converts VRML files to X3D embedded in HTML.
.SH "SEE ALSO"
.PP
dispcalGUI (1)
.SH "AUTHOR"
.PP
Florian Höch <dispcalgui@hoech.net>