.TH "dispcalGUI-testchart-editor" "1" "07 Jan 2013" "" ""

.SH NAME
dispcalGUI-testchart-editor \- Testchart editor
.SH SYNOPSIS

\fBdispcalGUI-testchart-editor\fR

.SH "DESCRIPTION"
.PP
Edits and generates testcharts.
.SH "SEE ALSO"
.PP
dispcalGUI (1)
.SH "AUTHOR"
.PP
Florian Höch <dispcalgui@hoech.net>