.TH "displaycal" "1" "24 July 2010" "" ""

.SH NAME
DisplayCAL \- Display calibration and characterization powered by ArgyllCMS
.SH SYNOPSIS

\fBdisplaycal\fR

.SH "DESCRIPTION"
.PP
A display calibration and profiling solution with a focus on accuracy and
versatility.
.PP
Calibrate and characterize your display devices using one of many supported 
measurement instruments, with support for multi-display setups and a variety of 
available options for advanced users, such as verification and reporting 
functionality to evaluate ICC profiles and display devices, creating video 3D 
LUTs, as well as optional CIECAM02 gamut mapping to take into account varying 
viewing conditions.
.SH "SEE ALSO"
.PP
displaycal-apply-profiles (1)
.SH "AUTHOR"
.PP
Florian Höch <displaycal@hoech.net>