.TH "displaycal-testchart-editor" "1" "07 Jan 2013" "" ""

.SH NAME
displaycal-testchart-editor \- Testchart editor
.SH SYNOPSIS

\fBdisplaycal-testchart-editor\fR

.SH "DESCRIPTION"
.PP
Edits and generates testcharts.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>