.TH "displaycal-synthprofile" "1" "06 May 2013" "" ""

.SH NAME
displaycal-synthprofile \- Synthetic Profile Creator
.SH SYNOPSIS

\fBdisplaycal-synthprofile\fR

.SH "DESCRIPTION"
.PP
Creates synthethic ICC profiles.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>