.TH "dispcalGUI-profile-info" "1" "07 Jan 2013" "" ""

.SH NAME
dispcalGUI-profile-info \- ICC profile information
.SH SYNOPSIS

\fBdispcalGUI-profile-info\fR

.SH "DESCRIPTION"
.PP
Shows ICC profile information like gamut, curves and embedded metadata.
.SH "SEE ALSO"
.PP
dispcalGUI (1)
.SH "AUTHOR"
.PP
Florian Höch <dispcalgui@hoech.net>