.TH "displaycal-scripting-client" "1" "03 Oct 2014" "" ""

.SH NAME
displaycal-scripting-client \- Scripting Client
.SH SYNOPSIS

\fBdisplaycal-scripting-client\fR

.SH "DESCRIPTION"
.PP
Control DisplayCAL via simple scripting commands.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>