.TH "displaycal-3dlut-maker" "1" "07 Jan 2013" "" ""

.SH NAME
displaycal-3dlut-maker \- 3D LUT creator
.SH SYNOPSIS

\fBdisplaycal-3dlut-maker\fR

.SH "DESCRIPTION"
.PP
Creates 3D LUTs from a chain of ICC profiles.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>