.TH "dispcalGUI-synthprofile" "1" "06 May 2013" "" ""

.SH NAME
dispcalGUI-synthprofile \- Synthetic Profile Creator
.SH SYNOPSIS

\fBdispcalGUI-synthprofile\fR

.SH "DESCRIPTION"
.PP
Creates synthethic ICC profiles.
.SH "SEE ALSO"
.PP
dispcalGUI (1)
.SH "AUTHOR"
.PP
Florian Höch <dispcalgui@hoech.net>