.TH "displaycal-vrml-to-x3d-converter" "1" "12 Apr 2014" "" ""

.SH NAME
displaycal-vrml-to-x3d-converter \- VRML to X3D converter
.SH SYNOPSIS

\fBdisplaycal-vrml-to-x3d-converter\fR

.SH "DESCRIPTION"
.PP
Converts VRML files to X3D embedded in HTML.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>