.TH "displaycal-curve-viewer" "1" "06 Jan 2014" "" ""

.SH NAME
displaycal-curve-viewer \- ICC profile information
.SH SYNOPSIS

\fBdisplaycal-curve-viewer\fR

.SH "DESCRIPTION"
.PP
Shows video card gamma table and profile tone response curves.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>