.TH "dispcalGUI-scripting-client" "1" "03 Oct 2014" "" ""

.SH NAME
dispcalGUI-scripting-client \- Scripting Client
.SH SYNOPSIS

\fBdispcalGUI-scripting-client\fR

.SH "DESCRIPTION"
.PP
Control dispcalGUI via simple scripting commands.
.SH "SEE ALSO"
.PP
dispcalGUI (1)
.SH "AUTHOR"
.PP
Florian Höch <dispcalgui@hoech.net>