.TH "displaycal-apply-profiles" "1" "24 July 2010" "" ""

.SH NAME
displaycal-apply-profiles \- ICC profile loader
.SH SYNOPSIS

\fBdisplaycal-apply-profiles\fR

.SH "DESCRIPTION"
.PP
Sets ICC profiles and loads calibration curves for all configured screens.
.PP
Compatible with ArgyllCMS (dispwin), Oyranos (oyranos-monitor) and colord.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>