.TH "displaycal-profile-info" "1" "07 Jan 2013" "" ""

.SH NAME
displaycal-profile-info \- ICC profile information
.SH SYNOPSIS

\fBdisplaycal-profile-info\fR

.SH "DESCRIPTION"
.PP
Shows ICC profile information like gamut, curves and embedded metadata.
.SH "SEE ALSO"
.PP
displaycal (1)
.SH "AUTHOR"
.PP
Florian Höch <florian_at_displaycal.net>