install_dir=`dirname "$0"`
echo "[Desktop Entry]">"$TMPDIR/dispcalGUI.desktop"
echo "Version=1.0">>"$TMPDIR/dispcalGUI.desktop"
echo "Type=Application">>"$TMPDIR/dispcalGUI.desktop"
echo "Name=dispcalGUI">>"$TMPDIR/dispcalGUI.desktop"
echo "Exec=\"$install_dir/dispcalGUI\"">>"$TMPDIR/dispcalGUI.desktop"
echo "Icon=$install_dir/theme/icons/48x48/dispcalGUI.png">>"$TMPDIR/dispcalGUI.desktop"
echo "Terminal=true">>"$TMPDIR/dispcalGUI.desktop"
echo "Categories=Graphics">>"$TMPDIR/dispcalGUI.desktop"
"$install_dir/xdg-desktop-icon.sh" install --novendor "$TMPDIR/dispcalGUI.desktop"
rm -f "$TMPDIR/dispcalGUI.desktop"
