#!/usr/bin/env python
# -*- coding: utf-8 -*-

import dispcalGUI
if hasattr(dispcalGUI, "main"):
	# running from source directly?
	main = dispcalGUI.main
else:
	# running from installed source?
	from dispcalGUI.dispcalGUI import main

main()