install_dir=`dirname "$0"`
echo "Installing binary to /usr/local/bin..."
cp -f "$install_dir/dispcalGUI" "/usr/local/bin"
echo "Installing language files to /usr/local/share/dispcalGUI/lang..."
mkdir -p "/usr/local/share/dispcalGUI"
cp -f -r "$install_dir/lang" "/usr/local/share/dispcalGUI"
echo "Installing documentation to /usr/local/doc/dispcalGUI..."
mkdir -p "/usr/local/doc/dispcalGUI/theme/icons"
cp -f -r "$install_dir/LICENSE.txt" "$install_dir/README.html" "$install_dir/screenshots" "/usr/local/doc/dispcalGUI"
cp -f "$install_dir/theme/header-readme.png" "/usr/local/doc/dispcalGUI/theme"
cp -f "$install_dir/theme/icons/favicon.ico" "/usr/local/doc/dispcalGUI/theme/icons"
echo "Installing icon resources..."
xdg-icon-resource install --noupdate --novendor --size 16 "$install_dir/theme/icons/16x16/dispcalGUI.png"
xdg-icon-resource install --noupdate --novendor --size 22 "$install_dir/theme/icons/22x22/dispcalGUI.png"
xdg-icon-resource install --noupdate --novendor --size 24 "$install_dir/theme/icons/24x24/dispcalGUI.png"
xdg-icon-resource install --noupdate --novendor --size 32 "$install_dir/theme/icons/32x32/dispcalGUI.png"
xdg-icon-resource install --noupdate --novendor --size 48 "$install_dir/theme/icons/48x48/dispcalGUI.png"
xdg-icon-resource install --noupdate --novendor --size 256 "$install_dir/theme/icons/256x256/dispcalGUI.png"
xdg-icon-resource forceupdate
echo "Installing desktop menu entry..."
xdg-desktop-menu install --novendor "$install_dir/dispcalGUI.desktop"
echo "...done"
