#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Only used on Windows to create standalone executable for task scheduler task

import sys

if sys.platform != "win32" or not getattr(sys, "frozen", False):
	print "This stub is only used by py2exe on Windows."
	sys.exit(1)

import subprocess as sp

# Strip "-launcher" from executable name
apply_profiles = sys.executable[:-13] + ".exe"

sp.Popen([apply_profiles, "--task"], stdin=sp.PIPE, stdout=sp.PIPE,
		 stderr=sp.STDOUT)
