#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys


if sys.platform == "win32" and not ("--help" in sys.argv[1:] or
									"-V" in sys.argv[1:] or
									"--version" in sys.argv[1:]):
	from DisplayCAL.main import main

	main("apply-profiles")
else:
	# Linux
	from DisplayCAL.profile_loader import main

	main()
