#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

if sys.platform == "win32":
	# Setup sys.path for running frozen
	# i.e. add C:\Program Files\dispcalGUI\lib\library.zip
	libpath = "\\".join(sys.executable.replace("/", "\\").split("\\")[:-1]) + "\\library.zip"
	sys.path.insert(0, libpath)

import os

if sys.platform == "win32" and os.path.isfile(libpath):
	sys.frozen = True

parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if not getattr(sys, "frozen", False):
	# Setup sys.path if running from source
	if os.path.exists(os.path.join(parent_dir, "dispcalGUI", "__init__.py")):
		sys.path.insert(0, parent_dir)

from dispcalGUI import config

if getattr(sys, "frozen", False):
	# Add script parent directory to data directories if running frozen
	config.data_dirs.insert(0, parent_dir)

# Python version check
from dispcalGUI.meta import py_minversion, py_maxversion

pyver = sys.version_info[:2]
if pyver < py_minversion or pyver > py_maxversion:
	raise RuntimeError("Need Python version >= %s <= %s, got %s" % 
					   (".".join(str(n) for n in py_minversion),
						".".join(str(n) for n in py_maxversion),
					    sys.version.split()[0]))

from dispcalGUI.wxLUT3DFrame import main

main()
